# Generated by Django 5.1.1 on 2024-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility')], default='Strength', max_length=50),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Beginner', max_length=50),
        ),
    ]
